version: '3'

services:
  database:
    container_name: CITIZEN-REGISTRAR
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - waf.env
    volumes:
      - /var/lib/postgresql/data
